# main menu
[[main]]
name = "About"
url = "about/"
weight = 1

# [[main]]
# name = "Blog"
# url = "blog/"
# weight = 3

[[main]]
weight = 4
name = "Extras"
hasChildren = true

  [[main]]
  parent = "Extras"
  name = "Research Tools"
  url = "http://tools.kausalflow.com/"
  weight = 1

  [[main]]
  parent = "Extras"
  name = "Hugo Connectome Theme"
  url = "https://hugo-connectome.kausalflow.com/graph/"
  weight = 7

# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

# [[footer]]
# name = "Blog"
# url = "blog/"
# weight = 2

# [[footer]]
# name = "Blog Details"
# url = "blog/post-1/"
# weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4